"""
signals.py — the two independent detection signals for Provenance Guard.

Signal 1 (get_llm_signal): holistic, semantic — asks an LLM (Groq) whether
the text reads as AI-generated. Captures meaning/style holistically.

Signal 2 (get_stylometric_signal): structural, statistical — pure Python
heuristics on sentence-length variance, vocabulary diversity, and
punctuation density. Captures measurable uniformity, independent of meaning.

Both return a float in [0, 1] representing "probability this text is
AI-generated" so they can be combined by scoring.py.
"""
import json
import os
import re
import statistics

LLM_MODEL = "llama-3.3-70b-versatile"

_SYSTEM_PROMPT = (
    "You are a text-provenance analyst. Given a piece of writing, estimate "
    "the probability it was generated by an AI language model rather than "
    "written by a human. Consider generic phrasing, hedge-heavy transitions "
    "('it is important to note', 'furthermore'), lack of concrete specific "
    "detail, and overly balanced tone as signs of AI generation. Consider "
    "idiosyncratic word choice, digressions, concrete personal detail, and "
    "uneven pacing as signs of human writing. "
    "Respond with ONLY a JSON object, no other text: "
    '{"probability_ai": <float between 0 and 1>, "reason": "<one sentence>"}'
)


def _clamp(value, lo=0.0, hi=1.0):
    return max(lo, min(hi, value))


def get_llm_signal(text):
    """
    Returns (score: float in [0,1], rationale: str, available: bool).

    If no GROQ_API_KEY is configured (or the call fails for any reason),
    falls back to a neutral score with available=False so the rest of the
    pipeline degrades gracefully instead of crashing. This lets the app run
    end-to-end without a key; drop a real key into .env to activate the
    live LLM signal.
    """
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        return 0.5, "LLM signal unavailable (no GROQ_API_KEY set) — neutral fallback used.", False

    try:
        from groq import Groq

        client = Groq(api_key=api_key)
        completion = client.chat.completions.create(
            model=LLM_MODEL,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
            temperature=0.0,
            max_tokens=150,
        )
        raw = completion.choices[0].message.content.strip()

        match = re.search(r"\{.*\}", raw, re.DOTALL)
        payload = json.loads(match.group(0) if match else raw)
        score = _clamp(float(payload.get("probability_ai", 0.5)))
        reason = str(payload.get("reason", "")).strip() or "No rationale returned."
        return score, reason, True
    except Exception as exc:  # noqa: BLE001 — deliberate broad fallback
        return 0.5, f"LLM signal error, neutral fallback used: {exc}", False


def _sentences(text):
    parts = re.split(r"(?<=[.!?])\s+", text.strip())
    return [p for p in parts if p.strip()]


def _words(text):
    return re.findall(r"[A-Za-z']+", text.lower())


def get_stylometric_signal(text):
    """
    Returns (score: float in [0,1], metrics: dict).

    Combines three structural sub-metrics, each mapped to an "AI-likeness"
    component in [0,1], then averages them:

      1. uniformity_component: low sentence-length variation -> higher score
         (AI text tends to keep sentences a fairly consistent length).
      2. ttr_component: low vocabulary diversity (type-token ratio) -> higher
         score (AI text tends to reuse a narrower working vocabulary).
      3. punctuation_component: punctuation density close to a "typical
         prose" band -> higher score (human writing more often drifts to
         extremes — very sparse/casual or very heavy/expressive punctuation).

    Blind spot: all three are statistically noisy on very short texts, and
    none of them understand meaning, so deliberately repetitive human
    writing (e.g. poetry with refrains) can score as "AI-like" here even
    though a human wrote it.
    """
    sentences = _sentences(text)
    words = _words(text)
    total_words = len(words)

    if not sentences or total_words == 0:
        return 0.5, {
            "note": "insufficient text to compute stylometric metrics",
            "sentence_count": len(sentences),
            "word_count": total_words,
        }

    sentence_lengths = [len(_words(s)) for s in sentences if _words(s)]
    mean_len = statistics.mean(sentence_lengths) if sentence_lengths else 0
    stdev_len = statistics.pstdev(sentence_lengths) if len(sentence_lengths) > 1 else 0.0
    cv = (stdev_len / mean_len) if mean_len > 0 else 0.0
    uniformity_component = _clamp(1 / (1 + cv))

    unique_words = len(set(words))
    ttr = unique_words / total_words
    ttr_component = _clamp(1 - ttr)

    punctuation_marks = len(re.findall(r"[.,;:!?\-—–\"'()]", text))
    punct_density = (punctuation_marks / total_words) * 100
    punctuation_component = _clamp(1 - abs(punct_density - 11) / 15)

    score = round(
        (uniformity_component + ttr_component + punctuation_component) / 3, 4
    )

    metrics = {
        "sentence_count": len(sentences),
        "word_count": total_words,
        "mean_sentence_length_words": round(mean_len, 2),
        "stdev_sentence_length": round(stdev_len, 2),
        "coefficient_of_variation": round(cv, 3),
        "uniformity_component": round(uniformity_component, 3),
        "type_token_ratio": round(ttr, 3),
        "ttr_component": round(ttr_component, 3),
        "punctuation_per_100_words": round(punct_density, 2),
        "punctuation_component": round(punctuation_component, 3),
        "low_sample_warning": total_words < 40,
    }
    return _clamp(score), metrics
